// generated by build/tools.js
const _ = () => import("../sites/sample/Sample.vue")
const _sample_audiorecorder = () => import("../sites/sample/AudioRecorder.vue")
const _sample_echo = () => import("../sites/sample/Echo.vue")
const _sample_helloworld = () => import("../sites/sample/HelloWorld.vue")
const _sample_sample = () => import("../sites/sample/Sample.vue")

export default [
 {
  path: '/',
  component: _,
  name: '_'
 },
 {
  path: '/sample/audiorecorder',
  component: _sample_audiorecorder,
  name: '_sample_audiorecorder'
 },
 {
  path: '/sample/echo',
  component: _sample_echo,
  name: '_sample_echo'
 },
 {
  path: '/sample/helloworld',
  component: _sample_helloworld,
  name: '_sample_helloworld'
 },
 {
  path: '/sample/sample',
  component: _sample_sample,
  name: '_sample_sample'
 }
]
