// generated by build/tools.js
const _ = () => import("../sites/test/Test.vue")
const _test_test = () => import("../sites/test/Test.vue")

export default [
 {
  path: '/',
  component: _,
  name: '_'
 },
 {
  path: '/test/test',
  component: _test_test,
  name: '_test_test'
 }
]
